"""tablas_iniciales

Revision ID: 6480cccdfc69
Revises: 
Create Date: 2026-04-02 05:46:42.053994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6480cccdfc69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destinatario_tipo', sa.String(length=20), nullable=False),
    sa.Column('destinatario_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taller',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=False),
    sa.Column('direccion_texto', sa.String(length=250), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_activacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('tipo_mantenimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion_base', sa.Text(), nullable=False),
    sa.Column('intervalo_km', sa.Integer(), nullable=True),
    sa.Column('intervalo_dias', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('firebase_uid')
    )
    op.create_table('contenido_educativo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('taller_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('url_imagen', sa.String(length=500), nullable=True),
    sa.Column('url_video', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('informe_ia', sa.Text(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disponibilidad_taller',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('taller_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('cupos_totales', sa.SmallInteger(), nullable=False),
    sa.Column('cupos_ocupados', sa.SmallInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taller_id', 'fecha', 'hora_inicio', 'hora_fin', name='uq_disponibilidad')
    )
    op.create_table('servicio_taller',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('taller_id', sa.UUID(), nullable=False),
    sa.Column('tipo_mantenimiento_id', sa.UUID(), nullable=False),
    sa.Column('nombre_personalizado', sa.String(length=100), nullable=True),
    sa.Column('descripcion_personalizada', sa.Text(), nullable=True),
    sa.Column('tiempo_estimado_minutos', sa.SmallInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.ForeignKeyConstraint(['tipo_mantenimiento_id'], ['tipo_mantenimiento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taller_id', 'tipo_mantenimiento_id', name='uq_taller_tipo')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('marca', sa.String(length=80), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('kilometraje_actual', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recordatorio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=False),
    sa.Column('tipo_mantenimiento_id', sa.UUID(), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('kilometraje_programado', sa.Integer(), nullable=True),
    sa.Column('texto_personalizado', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tipo_mantenimiento_id'], ['tipo_mantenimiento.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('taller_id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=False),
    sa.Column('disponibilidad_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disponibilidad_id'], ['disponibilidad_taller.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mantenimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=False),
    sa.Column('taller_id', sa.UUID(), nullable=False),
    sa.Column('kilometraje_registro', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_realizado', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id')
    )
    op.create_table('reserva_servicio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('servicio_taller_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reserva.id'], ),
    sa.ForeignKeyConstraint(['servicio_taller_id'], ['servicio_taller.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id', 'servicio_taller_id', name='uq_reserva_servicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva_servicio')
    op.drop_table('mantenimiento')
    op.drop_table('reserva')
    op.drop_table('recordatorio')
    op.drop_table('vehiculo')
    op.drop_table('servicio_taller')
    op.drop_table('disponibilidad_taller')
    op.drop_table('contenido_educativo')
    op.drop_table('usuario')
    op.drop_table('tipo_mantenimiento')
    op.drop_table('taller')
    op.drop_table('notificacion')
    op.drop_table('administrador')
    # ### end Alembic commands ###
