"""cambiar_descripcion_por_activo

Revision ID: c866f81ea343
Revises: 1f9cd9f2f44d
Create Date: 2026-04-22 22:39:19.752592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c866f81ea343'
down_revision: Union[str, Sequence[str], None] = '1f9cd9f2f44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('especialidad', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.drop_column('especialidad', 'descripcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('especialidad', sa.Column('descripcion', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('especialidad', 'activo')
    # ### end Alembic commands ###
